[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./test/foundry/script/"}, { access = "read", path = "./deployments/"}]
memory_limit = 9223372036854775807
solc_version = "0.8.17"
